import type { HeroSectionSettings, ThemeSettings } from "./api-types";

// Per Section 6 - built-in presets, code only (no download/marketplace,
// Section 33). Applying one merges its themeSettings into the current
// draft and nudges the hero section's own layout (alignment/height) so
// "hero layout" actually differs per preset too, not just colors/fonts -
// everything else in the current draft (other section settings, content)
// is left untouched.
export interface ThemePreset {
  key: string;
  name: string;
  description: string;
  themeSettings: Omit<ThemeSettings, "preset" | "logoUrl" | "faviconUrl">;
  heroOverrides: Pick<HeroSectionSettings, "alignment" | "height">;
}

export const THEME_PRESETS: ThemePreset[] = [
  {
    key: "modern",
    name: "Modern",
    description: "Clean indigo, rounded corners, balanced spacing.",
    themeSettings: {
      colorPrimary: "#4F46E5",
      colorSecondary: "#0F172A",
      colorAccent: "#F59E0B",
      colorBackground: "#FFFFFF",
      colorSurface: "#FFFFFF",
      colorText: "#0F172A",
      colorTextMuted: "#64748B",
      fontHeading: "Inter",
      fontBody: "Inter",
      cornerRadius: 10,
      buttonStyle: "rounded",
      containerWidth: 1200,
      sectionSpacing: "comfortable",
      productCardStyle: "bordered",
    },
    heroOverrides: { alignment: "center", height: "medium" },
  },
  {
    key: "minimal",
    name: "Minimal",
    description: "Monochrome, square corners, generous whitespace.",
    themeSettings: {
      colorPrimary: "#111827",
      colorSecondary: "#111827",
      colorAccent: "#111827",
      colorBackground: "#FFFFFF",
      colorSurface: "#FFFFFF",
      colorText: "#111827",
      colorTextMuted: "#6B7280",
      fontHeading: "Inter",
      fontBody: "Inter",
      cornerRadius: 2,
      buttonStyle: "square",
      containerWidth: 1120,
      sectionSpacing: "spacious",
      productCardStyle: "minimal",
    },
    heroOverrides: { alignment: "left", height: "small" },
  },
  {
    key: "elegant",
    name: "Elegant",
    description: "Warm charcoal and gold, serif headings, refined spacing.",
    themeSettings: {
      colorPrimary: "#1C1917",
      colorSecondary: "#78716C",
      colorAccent: "#B45309",
      colorBackground: "#FAFAF9",
      colorSurface: "#FFFFFF",
      colorText: "#1C1917",
      colorTextMuted: "#78716C",
      fontHeading: "Playfair Display",
      fontBody: "Inter",
      cornerRadius: 4,
      buttonStyle: "square",
      containerWidth: 1200,
      sectionSpacing: "spacious",
      productCardStyle: "minimal",
    },
    heroOverrides: { alignment: "center", height: "large" },
  },
  {
    key: "bold",
    name: "Bold",
    description: "High-energy red and yellow, pill buttons, shadowed cards.",
    themeSettings: {
      colorPrimary: "#E11D48",
      colorSecondary: "#18181B",
      colorAccent: "#FACC15",
      colorBackground: "#FFFFFF",
      colorSurface: "#FFFFFF",
      colorText: "#18181B",
      colorTextMuted: "#52525B",
      fontHeading: "Poppins",
      fontBody: "Inter",
      cornerRadius: 16,
      buttonStyle: "pill",
      containerWidth: 1280,
      sectionSpacing: "comfortable",
      productCardStyle: "shadow",
    },
    heroOverrides: { alignment: "left", height: "large" },
  },
  {
    key: "fashion",
    name: "Fashion",
    description: "Editorial pink and serif type, soft shadowed product cards.",
    themeSettings: {
      colorPrimary: "#DB2777",
      colorSecondary: "#171717",
      colorAccent: "#F472B6",
      colorBackground: "#FFFFFF",
      colorSurface: "#FFF1F7",
      colorText: "#171717",
      colorTextMuted: "#737373",
      fontHeading: "Playfair Display",
      fontBody: "Inter",
      cornerRadius: 20,
      buttonStyle: "pill",
      containerWidth: 1200,
      sectionSpacing: "comfortable",
      productCardStyle: "shadow",
    },
    heroOverrides: { alignment: "center", height: "large" },
  },
  {
    key: "tech",
    name: "Tech",
    description: "Dark, futuristic blue and cyan with a geometric heading font.",
    themeSettings: {
      colorPrimary: "#3B82F6",
      colorSecondary: "#94A3B8",
      colorAccent: "#22D3EE",
      colorBackground: "#0B1220",
      colorSurface: "#111827",
      colorText: "#F1F5F9",
      colorTextMuted: "#94A3B8",
      fontHeading: "Space Grotesk",
      fontBody: "Inter",
      cornerRadius: 8,
      buttonStyle: "rounded",
      containerWidth: 1280,
      sectionSpacing: "comfortable",
      productCardStyle: "bordered",
    },
    heroOverrides: { alignment: "center", height: "medium" },
  },
  {
    key: "neon",
    name: "Neon",
    description: "Dark navy/black with purple-to-blue neon gradients - premium tech and gaming feel.",
    themeSettings: {
      colorPrimary: "#8B5CF6",
      colorSecondary: "#1E1B4B",
      colorAccent: "#3B82F6",
      colorBackground: "#05070F",
      colorSurface: "#0F1424",
      colorText: "#F8FAFC",
      colorTextMuted: "#94A3B8",
      fontHeading: "Space Grotesk",
      fontBody: "Inter",
      cornerRadius: 16,
      buttonStyle: "rounded",
      containerWidth: 1280,
      sectionSpacing: "comfortable",
      productCardStyle: "shadow",
    },
    heroOverrides: { alignment: "left", height: "large" },
  },
];
